version: "2.0"

services:
  elastic-kag:
    #image: docker.elastic.co/elasticsearch/elasticsearch:2.4.1
    image: elasticsearch:2.4.5
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
  kibana-kag:
    #image: docker.elastic.co/kibana/kibana:5.4.1
    image: kibana:4.6.4
    environment:
     - ELASTICSEARCH_URL=http://elastic-kag:9200
    ports:
      - "5601:5601"
  build-alpine-kag:
    build: build-alpine-kag
    volumes:
      - ../.:/project
    working_dir: /project
    environment:
      - GOPATH=/project/:/project/vendor/
    command: bash
  build-debian-kag:
    build: build-debian-kag
    volumes:
      - ../.:/project
    working_dir: /project
    environment:
      - GOPATH=/project/:/project/vendor/
    command: bash
